# Generated by Django 3.1.3 on 2020-11-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20201123_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='common',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
