# Generated by Django 3.1.3 on 2020-12-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_communities', '0001_initial'),
        ('interests', '0001_initial'),
        ('users', '0002_auto_20201202_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='communities',
            field=models.ManyToManyField(related_name='profiles', to='new_communities.NewCommunity'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(related_name='profiles', to='interests.Interest'),
        ),
    ]
