# Generated by Django 3.1.3 on 2020-12-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, to='interests.Interest'),
        ),
    ]
