# Generated by Django 3.1.3 on 2020-12-09 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20201207_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='interests',
        ),
    ]
