# Generated by Django 3.1.3 on 2020-11-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('new_communities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcommunity',
            name='activity',
        ),
        migrations.AddField(
            model_name='newcommunity',
            name='activities',
            field=models.ManyToManyField(to='activities.Activity'),
        ),
    ]
