# Generated by Django 3.1.3 on 2020-12-07 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('new_communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_communities.newcommunity')),
                ('join_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
