# Generated by Django 3.1.3 on 2020-12-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_communities', '0002_joinuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinuser',
            old_name='join_community',
            new_name='joinCommunity',
        ),
        migrations.RenameField(
            model_name='joinuser',
            old_name='join_user',
            new_name='joinUser',
        ),
    ]
