# Generated by Django 3.1.3 on 2020-12-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
        ('new_communities', '0002_auto_20201202_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcommunity',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, to='interests.Interest'),
        ),
    ]
