# Generated by Django 3.1.3 on 2020-12-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_communities', '0003_auto_20201207_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinuser',
            old_name='joinCommunity',
            new_name='community',
        ),
        migrations.RenameField(
            model_name='joinuser',
            old_name='joinUser',
            new_name='profile',
        ),
    ]
