# Generated by Django 3.1.3 on 2020-12-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_communities', '0004_auto_20201207_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinuser',
            name='text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
