# Generated by Django 3.1.3 on 2020-12-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_activity_interests'),
        ('interests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='activities',
            field=models.ManyToManyField(blank=True, null=True, to='activities.Activity'),
        ),
    ]
