# Generated by Django 3.1.3 on 2020-12-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
